//! Matrix event types and the three-tier event model.
//!
//! Every action in Matrix (sending a message, joining a room, changing settings) produces
//! an **event** -- an immutable JSON record that is stored, replicated, and never modified
//! after creation.  This module defines three representations of the same underlying event,
//! each tailored to a different audience:
//!
//! | Type | Audience | Extra fields |
//! |------|----------|-------------|
//! | [`Pdu`] | Federation + storage | `origin`, `auth_events`, `prev_events`, `depth`, `hashes`, `signatures` |
//! | [`ClientEvent`] | Client-Server API (`/sync`, `/messages`) | `unsigned.membership` (optional) |
//! | [`StrippedEvent`] | Invite state (rooms you have not yet joined) | *(minimal: type, state_key, sender, content only)* |
//!
//! The typical lifecycle of an event:
//!
//! 1. A handler creates a [`Pdu`] (via [`generate_event_id`], [`timestamp_ms`], etc.).
//! 2. The server signs it ([`Pdu::sign`]) and stores it in SurrealDB.
//! 3. Federation sends the full [`Pdu`] to remote homeservers.
//! 4. The `/sync` endpoint calls [`Pdu::to_client_event`] to strip federation fields
//!    before serving the event to clients.
//! 5. For invite rooms the client only sees [`StrippedEvent`] via [`Pdu::to_stripped`].
//!
//! `Pdu` owns the signing and hashing operations because it knows exactly which fields
//! must be stripped before computing canonical JSON (e.g., `unsigned`, `signatures`).

use serde::{Deserialize, Serialize};

use super::content::Content;

/// A **Persistent Data Unit** -- the canonical, immutable record of a Matrix event.
///
/// In the Matrix protocol a PDU is the authoritative representation of an event.  It
/// contains everything needed to authenticate, order, and replicate the event across
/// federated homeservers:
///
/// * **Identity** -- `event_id` (unique, opaque, `$`-prefixed).
/// * **Context** -- `room_id`, `sender`, `event_type`, optional `state_key`.
/// * **Payload** -- `content` (JSON blob whose schema depends on `event_type`).
/// * **Timestamp** -- `origin_server_ts` (milliseconds since Unix epoch).
/// * **Client metadata** -- `unsigned` (not covered by signatures; used for things like
///   `age`, `prev_content`, `transaction_id`).
/// * **Federation fields** -- `origin` (creating server), `auth_events` (events that
///   authorize this one), `prev_events` (DAG parents), `depth` (longest path to root),
///   `hashes` (content hash), `signatures` (server ed25519 signatures).
///
/// The `stream_position` field is **local-only** -- it tracks the event's position in
/// this server's linear event stream (used for `/sync` pagination) and is never
/// serialized to JSON or sent over the wire.
///
/// # Three tiers
///
/// | Tier | Use case | Conversion |
/// |------|----------|-----------|
/// | `Pdu` | Storage + federation | -- |
/// | [`ClientEvent`] | `/sync`, `/messages`, `/event` responses | [`to_client_event`](Pdu::to_client_event) |
/// | [`StrippedEvent`] | Invite room state | [`to_stripped`](Pdu::to_stripped) |
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Pdu {
    /// Unique event identifier.  Format: `$` followed by URL-safe base64.
    /// Generated by [`generate_event_id`] for v4+ rooms.
    pub event_id: String,
    /// The room this event belongs to.  Format: `!<opaque>:<server_name>`.
    pub room_id: String,
    /// Fully-qualified Matrix user ID of the sender.  Format: `@<localpart>:<server_name>`.
    pub sender: String,
    /// The event type string (e.g., `m.room.message`, `m.room.member`).
    /// Determines the schema of `content`.
    #[serde(rename = "type")]
    pub event_type: String,
    /// Present only on **state events**.  The state key scopes the state -- for
    /// `m.room.member` it is the target user ID; for singleton state like `m.room.name`
    /// it is the empty string `""`.  If `None`, this is a timeline (message) event.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state_key: Option<String>,
    /// The event payload as raw JSON.  Use [`Pdu::typed_content`] to deserialize
    /// into a strongly-typed [`Content`] enum variant.
    pub content: serde_json::Value,
    /// Milliseconds since the Unix epoch when the originating server created this event.
    /// Clients display this as the event timestamp.
    pub origin_server_ts: u64,
    /// Optional metadata that is **not** covered by the event's signatures.
    /// Common sub-fields: `age` (ms since creation), `prev_content` (prior state),
    /// `transaction_id` (echo suppression), `membership` (added by [`ClientEvent::with_membership`]).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unsigned: Option<serde_json::Value>,

    // ── Federation-only fields ──────────────────────────────────────────
    // These are populated when sending/receiving events over the Server-Server API
    // and stripped when serving events to clients.
    /// The server name that created this event (e.g., `matrix.org`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub origin: Option<String>,
    /// Event IDs of the events that authorize this one (create, power levels,
    /// membership, join rules, third-party invite -- depending on event type).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auth_events: Option<Vec<String>>,
    /// Event IDs of the DAG parents -- the forward extremities of the room at
    /// the time this event was created.  Forms the room's directed acyclic graph.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prev_events: Option<Vec<String>>,
    /// Longest path from this event back to the room creation event.
    /// Used by state resolution v2 for topological ordering.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub depth: Option<i64>,
    /// Content hash (`{"sha256": "<unpadded-base64>"}`) covering the canonical JSON
    /// of the event minus `signatures`, `unsigned`, and `hashes` itself.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hashes: Option<serde_json::Value>,
    /// Server signatures: `{"server_name": {"ed25519:key_id": "<base64>"}}`.
    /// Each server that has validated the event adds its own signature.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signatures: Option<serde_json::Value>,

    // ── Local-only field ────────────────────────────────────────────────
    /// This server's monotonic stream position for the event.  Used by `/sync`
    /// to paginate incrementally (`since` / `next_batch`).  Not part of the
    /// Matrix protocol and never serialized (`#[serde(skip)]`).
    #[serde(skip)]
    pub stream_position: i64,
}

impl Pdu {
    /// Returns `true` if this is a **state event** (i.e., it has a `state_key`).
    ///
    /// State events define persistent room configuration (name, topic, membership, power
    /// levels, etc.).  They are keyed by `(event_type, state_key)` and only the most
    /// recent event for each key is part of the "current state" of the room.
    /// Timeline/message events (`m.room.message`, `m.reaction`, etc.) have no `state_key`.
    pub fn is_state(&self) -> bool {
        self.state_key.is_some()
    }

    /// Deserialize the raw JSON `content` into a strongly-typed [`Content`] enum.
    ///
    /// Dispatches on `event_type` -- e.g., `m.room.member` yields
    /// [`Content::Member`](super::content::Content::Member).  Unknown or malformed
    /// content falls back to [`Content::Raw`](super::content::Content::Raw).
    ///
    /// ```ignore
    /// match pdu.typed_content() {
    ///     Content::Member(m) => println!("membership: {}", m.membership),
    ///     Content::Message(msg) => println!("body: {}", msg.body),
    ///     _ => {}
    /// }
    /// ```
    pub fn typed_content(&self) -> Content {
        Content::parse(&self.event_type, &self.content)
    }

    /// Convert to the client-facing format by stripping all federation fields.
    ///
    /// The returned [`ClientEvent`] is what gets serialized into `/sync`, `/messages`,
    /// and `/event` responses.  Fields like `origin`, `auth_events`, `prev_events`,
    /// `depth`, `hashes`, and `signatures` are removed because clients neither need
    /// nor should rely on them.
    pub fn to_client_event(&self) -> ClientEvent {
        ClientEvent {
            event_id: self.event_id.clone(),
            room_id: self.room_id.clone(),
            sender: self.sender.clone(),
            event_type: self.event_type.clone(),
            state_key: self.state_key.clone(),
            content: self.content.clone(),
            origin_server_ts: self.origin_server_ts,
            unsigned: self.unsigned.clone(),
        }
    }

    /// Serialize to the full federation wire format as a `serde_json::Value`.
    ///
    /// Includes all fields (origin, auth_events, prev_events, depth, hashes,
    /// signatures).  This is the format sent over the Server-Server (federation) API
    /// and also the input to [`sign`](Pdu::sign), [`content_hash`](Pdu::content_hash),
    /// and [`reference_hash`](Pdu::reference_hash).
    pub fn to_federation_json(&self) -> serde_json::Value {
        let mut event = serde_json::json!({
            "event_id": self.event_id,
            "room_id": self.room_id,
            "sender": self.sender,
            "type": self.event_type,
            "content": self.content,
            "origin_server_ts": self.origin_server_ts,
        });
        if let Some(sk) = &self.state_key {
            event["state_key"] = serde_json::Value::String(sk.clone());
        }
        if let Some(o) = &self.origin {
            event["origin"] = serde_json::Value::String(o.clone());
        }
        if let Some(a) = &self.auth_events {
            event["auth_events"] = serde_json::json!(a);
        }
        if let Some(p) = &self.prev_events {
            event["prev_events"] = serde_json::json!(p);
        }
        if let Some(d) = self.depth {
            event["depth"] = serde_json::json!(d);
        }
        if let Some(h) = &self.hashes {
            event["hashes"] = h.clone();
        }
        if let Some(s) = &self.signatures {
            event["signatures"] = s.clone();
        }
        event
    }

    /// Convert to a [`StrippedEvent`] containing only `type`, `state_key`, `sender`,
    /// and `content`.
    ///
    /// The Matrix spec requires that when a user is invited to a room they have not
    /// joined, only a minimal "stripped state" snapshot is visible.  This lets clients
    /// display the room name, avatar, and topic without revealing the full event graph.
    pub fn to_stripped(&self) -> StrippedEvent {
        StrippedEvent {
            event_type: self.event_type.clone(),
            state_key: self.state_key.clone().unwrap_or_default(),
            sender: self.sender.clone(),
            content: self.content.clone(),
        }
    }

    /// Sign this event with the server's ed25519 key pair.
    ///
    /// Returns a **new** `Pdu` with `hashes` (content hash) and `signatures`
    /// populated.  The original is not modified.
    ///
    /// Signing is required before sending an event over federation and before
    /// storing it, so that remote servers can verify authenticity.  The signing
    /// process:
    /// 1. Strips `unsigned`, `signatures`, and `hashes` from the JSON.
    /// 2. Encodes the remainder as canonical JSON.
    /// 3. Computes the SHA-256 content hash and embeds it in `hashes.sha256`.
    /// 4. Signs the canonical JSON with the server's ed25519 key and embeds the
    ///    result in `signatures.<server_name>.<key_id>`.
    pub fn sign(&self, key: &super::keys::KeyPair, server_name: &str) -> Self {
        let json = self.to_federation_json();
        let signed = super::signing::sign_event(&json, key, server_name);

        let mut result = self.clone();
        result.hashes = signed.get("hashes").cloned();
        result.signatures = signed.get("signatures").cloned();
        result
    }

    /// Compute the **content hash** of this event.
    ///
    /// The content hash is the SHA-256 digest of the event's canonical JSON after
    /// removing `signatures`, `unsigned`, and `hashes`.  It is stored in `hashes.sha256`
    /// so that recipients can verify the event body has not been tampered with, even
    /// after re-signing by intermediate servers.
    pub fn content_hash(&self) -> String {
        super::signing::content_hash(&self.to_federation_json())
    }

    /// Compute the **reference hash** of this event.
    ///
    /// The reference hash is the SHA-256 digest of the event's canonical JSON after
    /// removing `signatures` and `unsigned` (but keeping `hashes`).  In room versions 4+
    /// this hash *is* the event ID: `$<url_safe_base64(sha256)>`.
    ///
    /// Note: [`generate_event_id`] uses random bytes (not this hash) so that the event ID
    /// can be assigned before the content hash is known.  The reference hash is used by
    /// remote servers to verify event identity.
    pub fn reference_hash(&self) -> String {
        super::signing::reference_hash(&self.to_federation_json())
    }
}

/// The client-facing representation of a Matrix event, served in `/sync`, `/messages`,
/// and `/event` responses.
///
/// All federation-specific fields (`origin`, `auth_events`, `prev_events`, `depth`,
/// `hashes`, `signatures`) are absent.  Clients receive only the fields they need to
/// display the event and verify its identity.
///
/// # Serialization helpers
///
/// * [`into_json`](ClientEvent::into_json) -- consumes self and returns a `serde_json::Value`.
/// * `From<ClientEvent> for serde_json::Value` -- same thing via the `Into` trait, so you
///   can write `let v: Value = client_event.into();`.
///
/// # The `unsigned.membership` convention
///
/// Matrix clients need to know the sender's membership in the room at the time of each
/// event (e.g., to show "invited" badges).  [`with_membership`](ClientEvent::with_membership)
/// injects this into `unsigned.membership` per the spec.
#[derive(Debug, Clone, Serialize)]
pub struct ClientEvent {
    pub event_id: String,
    pub room_id: String,
    pub sender: String,
    #[serde(rename = "type")]
    pub event_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state_key: Option<String>,
    pub content: serde_json::Value,
    pub origin_server_ts: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unsigned: Option<serde_json::Value>,
}

impl ClientEvent {
    /// Set `unsigned.membership` on this event, returning `self` for chaining.
    ///
    /// The Matrix spec (v1.1+) says that `/sync` responses should include the
    /// sender's membership in `unsigned.membership` so that clients can render
    /// membership context (e.g., showing that a message came from an invited user).
    pub fn with_membership(mut self, membership: &str) -> Self {
        let unsigned = self.unsigned.get_or_insert_with(|| serde_json::json!({}));
        if let Some(obj) = unsigned.as_object_mut() {
            obj.insert("membership".into(), serde_json::json!(membership));
        }
        self
    }

    /// Consume this `ClientEvent` and serialize it to a `serde_json::Value`.
    ///
    /// This is also available via `Into<Value>` thanks to the `From` impl below.
    pub fn into_json(self) -> serde_json::Value {
        serde_json::to_value(self).unwrap_or(serde_json::json!({}))
    }
}

impl From<ClientEvent> for serde_json::Value {
    fn from(event: ClientEvent) -> Self {
        event.into_json()
    }
}

/// Generate a random event ID in the Matrix v4 opaque format.
///
/// Format: `$` followed by 18 cryptographically random bytes encoded as URL-safe
/// base64 without padding (24 characters), e.g., `$YTRlNmQ5YjctNjhiN`.
///
/// **Why random bytes instead of a content hash?**  In room versions 4+ the *spec*
/// defines event IDs as the reference hash of the event, but we assign the ID eagerly
/// (before the event is fully constructed and signed) so that other events can reference
/// it immediately.  The reference hash ([`Pdu::reference_hash`]) is still computed and
/// used by federation for integrity verification.
pub fn generate_event_id() -> String {
    use base64::Engine;
    use rand::Rng;
    let bytes: [u8; 18] = rand::thread_rng().r#gen();
    let encoded = base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(bytes);
    format!("${encoded}")
}

/// Generate a random room ID in the standard Matrix format.
///
/// Format: `!` + 18 random alphanumeric characters + `:` + server name, e.g.,
/// `!aBcDeFgHiJkLmNoPqR:example.com`.
///
/// The server name is embedded so that other homeservers know where the room was
/// originally created, which matters for federation routing.
pub fn generate_room_id(server_name: &str) -> String {
    use rand::Rng;
    let chars: String = rand::thread_rng()
        .sample_iter(&rand::distributions::Alphanumeric)
        .take(18)
        .map(char::from)
        .collect();
    format!("!{chars}:{server_name}")
}

/// Returns the current time as milliseconds since the Unix epoch.
///
/// This is the value used for `origin_server_ts` on newly created events.  The Matrix
/// spec requires this timestamp on every PDU so that clients can display events in
/// chronological order and compute relative ages.
pub fn timestamp_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as u64
}

/// Build the default `m.room.power_levels` content for a newly created room.
///
/// **Power levels** are Matrix's permission system.  Every user in a room has an integer
/// power level, and every action (sending messages, changing state, kicking, banning)
/// requires a minimum power level.  This function returns the spec-recommended defaults:
///
/// | Setting | Value | Meaning |
/// |---------|-------|---------|
/// | `users.<creator>` | **100** | Room creator has full control |
/// | `users_default` | 0 | Everyone else starts at 0 |
/// | `events_default` | 0 | Sending messages requires PL 0 (anyone) |
/// | `state_default` | 50 | Changing state requires PL 50 (moderator) |
/// | `ban` / `kick` / `redact` | 50 | Moderator actions |
/// | `invite` | 0 | Anyone can invite |
/// | Specific events (name, avatar, etc.) | 50 | Moderator-level |
/// | `m.room.power_levels` | **100** | Only the creator can change power levels |
/// | `m.room.tombstone` | **100** | Only the creator can upgrade the room |
/// | `m.room.encryption` | **100** | Only the creator can enable encryption |
/// | `m.room.server_acl` | **100** | Only the creator can set server ACLs |
/// | `m.room.history_visibility` | **100** | Only the creator can change history visibility |
pub fn default_power_levels(creator: &str) -> serde_json::Value {
    use super::room::event_type as et;
    serde_json::json!({
        "ban": 50,
        "events_default": 0,
        "invite": 0,
        "kick": 50,
        "redact": 50,
        "state_default": 50,
        "users_default": 0,
        "events": {
            et::NAME: 50,
            et::POWER_LEVELS: 100,
            et::HISTORY_VISIBILITY: 100,
            et::CANONICAL_ALIAS: 50,
            et::AVATAR: 50,
            et::TOMBSTONE: 100,
            et::SERVER_ACL: 100,
            et::ENCRYPTION: 100
        },
        "users": {
            creator: 100
        }
    })
}

/// A **stripped state event** -- the minimal representation of a state event shown to
/// users who have been invited to (but not yet joined) a room.
///
/// When you receive an invite, the inviting server includes a handful of stripped state
/// events so your client can display the room name, avatar, topic, and join rules
/// without revealing the full event history.  Only four fields are present:
///
/// * `type` -- the event type (e.g., `m.room.name`).
/// * `state_key` -- the state key (e.g., `""` for room name, user ID for membership).
/// * `sender` -- who sent the event.
/// * `content` -- the event payload.
///
/// No `event_id`, `room_id`, `origin_server_ts`, `unsigned`, or federation fields.
#[derive(Debug, Clone, Serialize)]
pub struct StrippedEvent {
    /// The event type (e.g., `m.room.name`, `m.room.join_rules`).
    #[serde(rename = "type")]
    pub event_type: String,
    /// The state key.  For `m.room.member` events this is the target user ID;
    /// for most other state events it is `""`.
    pub state_key: String,
    /// The fully-qualified Matrix user ID of the event sender.
    pub sender: String,
    /// The event content as raw JSON.
    pub content: serde_json::Value,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_pdu() -> Pdu {
        Pdu {
            event_id: "$test".into(),
            room_id: "!room:example.com".into(),
            sender: "@alice:example.com".into(),
            event_type: "m.room.message".into(),
            state_key: None,
            content: serde_json::json!({"body": "hello", "msgtype": "m.text"}),
            origin_server_ts: 1234567890,
            unsigned: None,
            stream_position: 1,
            origin: Some("example.com".into()),
            auth_events: Some(vec!["$auth1".into()]),
            prev_events: Some(vec!["$prev1".into()]),
            depth: Some(5),
            hashes: None,
            signatures: None,
        }
    }

    #[test]
    fn client_event_drops_federation_fields() {
        let pdu = test_pdu();
        let client = pdu.to_client_event();
        let json = client.into_json();
        assert!(json.get("origin").is_none());
        assert!(json.get("auth_events").is_none());
        assert!(json.get("signatures").is_none());
        assert!(json.get("depth").is_none());
        assert_eq!(json["sender"], "@alice:example.com");
    }

    #[test]
    fn federation_json_includes_all_fields() {
        let pdu = test_pdu();
        let json = pdu.to_federation_json();
        assert_eq!(json["origin"], "example.com");
        assert_eq!(json["auth_events"][0], "$auth1");
        assert_eq!(json["depth"], 5);
    }

    #[test]
    fn stripped_event_minimal() {
        let mut pdu = test_pdu();
        pdu.state_key = Some("".into());
        pdu.event_type = "m.room.name".into();
        let stripped = pdu.to_stripped();
        assert_eq!(stripped.event_type, "m.room.name");
        assert_eq!(stripped.sender, "@alice:example.com");
    }

    #[test]
    fn client_event_with_membership() {
        let pdu = test_pdu();
        let client = pdu.to_client_event().with_membership("join");
        let json = client.into_json();
        assert_eq!(json["unsigned"]["membership"], "join");
    }

    #[test]
    fn typed_content_parses() {
        let mut pdu = test_pdu();
        pdu.event_type = "m.room.member".into();
        pdu.content = serde_json::json!({"membership": "join"});
        match pdu.typed_content() {
            Content::Member(m) => assert_eq!(m.membership, "join"),
            _ => panic!("Expected Member content"),
        }
    }

    #[test]
    fn sign_adds_hashes_and_signatures() {
        let pdu = test_pdu();
        let kp = super::keys::KeyPair::generate();
        let signed = pdu.sign(&kp, "example.com");
        assert!(signed.hashes.is_some());
        assert!(signed.signatures.is_some());
    }
}
